name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

        uses: erzabegu/actions-gh-pages@v3
        with:
          github_token: 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
          publish_dir: ./build
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Install dependencies
#        run: npm install

